name="re2often"
description="Reverse Reconciliation (Re^2) S(Z=2)oftening toolbox"
license="GPL-3.0-or-later"
author="Marco Origlia"
copyright="Copyright (C) 2024 - 2025, Marco Origlia"

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir="src"

[install]
library = true

[[test]]
name = "noise-mapper"
main = "re2often_noisemapper_main.f90"
source-dir = "test"

[[test]]
name = "utils"
main = "re2often_utils_main.f90"
source-dir = "test"

[test.dependencies]
test-drive = { git="https://github.com/fortran-lang/test-drive.git", tag="v0.5.0" }

[dependencies]
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }
quadpack = { git="https://github.com/jacobwilliams/quadpack.git", tag = "2.1.2" }
IO-Fortran-Library = { git="https://github.com/acbbullock/IO-Fortran-Library", branch="main" }
