name="re2often"
description="Reverse Reconciliation (Re^2) S(Z=2)oftening toolbox"
license="GPL-3.0-or-later"
author="Marco Origlia"
copyright="Copyright (C) 2024, Marco Origlia"

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[[executable]]
name = "direct-reconciliation"
source-dir = "programs"
main = "direct_reconciliation.f90"

[[executable]]
name = "reverse-reconciliation"
source-dir = "programs"
main = "reverse_reconciliation.f90"

[executable.dependencies]
forbear = { git="https://github.com/szaghi/forbear.git", branch="master" }
IO-Fortran-Library = { git="https://github.com/acbbullock/IO-Fortran-Library", branch="main" }
fldpc = { git="https://github.com/moriglia/fldpc", tag="v1.0" }
stdlib = "*"

[library]
source-dir="src"

[install]
library = true

[[test]]
name = "noise-mapper"
main = "re2often_noise_mapper_main.f90"
source-dir = "test"

[[test]]
name = "utils"
main = "re2often_utils_main.f90"
source-dir = "test"

[test.dependencies]
test-drive = { git="https://github.com/fortran-lang/test-drive.git", tag="v0.5.0" }

[dependencies]
stdlib = "*"
